var regionais = [
{bairro: "1º de Maio", regional: "Norte", bairroBHTrans: ""},
{bairro: "Aarão Reis", regional: "Norte", bairroBHTrans: ""},
{bairro: "Abadia", regional: "Leste", bairroBHTrans: ""},
{bairro: "Adalberto Ferraz", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Aeroporto", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Afonso Pena", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Alto Barroca", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Alto da Boa Vista", regional: "Leste", bairroBHTrans: ""},
{bairro: "Alto dos Caiçaras", regional: "Noroeste", bairroBHTrans: "ALTO CAICARA"},
{bairro: "Alto dos Pinheiros", regional: "Noroeste", bairroBHTrans: "ALTO DOS PINHEIROS"},
{bairro: "Alto Vera Cruz", regional: "Leste", bairroBHTrans: "ALTO VERA CRUZ"},
{bairro: "Alípio de Melo", regional: "Noroeste", bairroBHTrans: "ALIPIO DE MELO"},
{bairro: "Américo Wernek (antigo Colônia/Floresta)", regional: "Leste", bairroBHTrans: ""},
{bairro: "Ana Lúcia", regional: "Leste", bairroBHTrans: ""},
{bairro: "Anchieta", regional: "Centro-Sul", bairroBHTrans: "ANCHIETA"},
{bairro: "Antiga Cidade da Serra", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Aparecida Sétima Seção", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Aparecida", regional: "Noroeste", bairroBHTrans: "APARECIDA"},
{bairro: "Araguaia", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Austim", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Bairro da Graça", regional: "Leste", bairroBHTrans: ""},
{bairro: "Bairro da Graça", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Bairro das Industrias", regional: "Oeste", bairroBHTrans: "BAIRRO DAS INDUSTRIAS 4A SECAO"},
{bairro: "Bairro das Indústrias I", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Bairro das Manções", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Baleia", regional: "Leste", bairroBHTrans: "BALEIA"},
{bairro: "Bandeirantes", regional: "Pampulha", bairroBHTrans: "BANDEIRANTES"},
{bairro: "Barreiro", regional: "Barreiro", bairroBHTrans: "BARREIRO"},
{bairro: "Barro Preto", regional: "Centro-Sul", bairroBHTrans: "BARRO PRETO"},
{bairro: "Barroca", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Beija-Flor", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Beira Linha (parte da Vila Dom Silvério, São Gabriel, Triba, Parque Belmonte e Jardim Belmonte)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Belmonte", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Belvedere", regional: "Oeste", bairroBHTrans: "BELVEDERE"},
{bairro: "Belém", regional: "Leste", bairroBHTrans: ""},
{bairro: "Betânia", regional: "Oeste", bairroBHTrans: "BETANIA"},
{bairro: "Bias Fortes (antigo Colônia/Santa Ifigênia)", regional: "Leste", bairroBHTrans: ""},
{bairro: "Boa Viagem", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Boa Vista", regional: "Leste", bairroBHTrans: "BOA VISTA"},
{bairro: "Bom Jesus", regional: "Noroeste", bairroBHTrans: "BOM JESUS"},
{bairro: "Bonfim", regional: "Noroeste", bairroBHTrans: "BONFIM"},
{bairro: "Bonsucesso", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Brasil Industrial", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Braúnas", regional: "Pampulha", bairroBHTrans: "BRAUNAS"},
{bairro: "Buraco Quente", regional: "Leste", bairroBHTrans: ""},
{bairro: "Buritis", regional: "Oeste", bairroBHTrans: "BURITIS"},
{bairro: "Cabana Pai Tomaz", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Cachoeirinha", regional: "Nordeste", bairroBHTrans: "CACHOEIRINHA"},
{bairro: "Caetano Furquim", regional: "Leste", bairroBHTrans: "CAETANO FURQUIM"},
{bairro: "Cafezal", regional: "Leste", bairroBHTrans: ""},
{bairro: "Caiçara Adelaide", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Caiçaras", regional: "Noroeste", bairroBHTrans: "CAICARA"},
{bairro: "Calafate", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Califórnia", regional: "Noroeste", bairroBHTrans: "CALIFORNIA"},
{bairro: "Camargos (parte)", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Camargos", regional: "Noroeste", bairroBHTrans: "CAMARGOS"},
{bairro: "Camponesa", regional: "Leste", bairroBHTrans: ""},
{bairro: "Canaã", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Candelária", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Capitão Eduardo", regional: "Nordeste", bairroBHTrans: "CAPITAO EDUARDO"},
{bairro: "Cardoso", regional: "Barreiro", bairroBHTrans: "CARDOSO"},
{bairro: "Carlos Prates", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Carmo", regional: "Centro-Sul", bairroBHTrans: "CARMO SION"},
{bairro: "Casa Branca", regional: "Leste", bairroBHTrans: "CASA BRANCA"},
{bairro: "Castanheira", regional: "Leste", bairroBHTrans: "CASTANHEIRAS"},
{bairro: "Castelo", regional: "Pampulha", bairroBHTrans: "CASTELO"},
{bairro: "Centro de Venda Nova", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Centro", regional: "Centro-Sul", bairroBHTrans: "AV. AFONSO PENA CENTRO"},
{bairro: "Cenáculo", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Cidade Jardim Taquaril", regional: "Leste", bairroBHTrans: ""},
{bairro: "Cidade Jardim", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Cidade Nova", regional: "Nordeste", bairroBHTrans: "CIDADE NOVA"},
{bairro: "Cidade Universitária", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Cinqüentenário", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Colégio Batista", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Comiteco", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Concórdia", regional: "Nordeste", bairroBHTrans: "CONCORDIA"},
{bairro: "Conjunto Ademar Maldonado", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Conjunto Betânia", regional: "Oeste", bairroBHTrans: "CONJUNTO BETANIA"},
{bairro: "Conjunto Boa Esperança", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Conjunto Bonsucesso", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Conjunto Califórnia Dois", regional: "Noroeste", bairroBHTrans: "CALIFORNIA II"},
{bairro: "Conjunto Califórnia", regional: "Noroeste", bairroBHTrans: "CONJUNTO CALIFORNIA"},
{bairro: "Conjunto Celso Machado", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Conjunto Confisco", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Conjunto Esperança", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Conjunto Estrela d'Alva", regional: "Oeste", bairroBHTrans: "ESTRELA DALVA"},
{bairro: "Conjunto Felicidade", regional: "Norte", bairroBHTrans: "CONJ. FELICIDADE"},
{bairro: "Conjunto Felicidade", regional: "Norte", bairroBHTrans: "CONJUNTO FELICIDADE"},
{bairro: "Conjunto Floramar", regional: "Norte", bairroBHTrans: ""},
{bairro: "Conjunto Flávio de Oliveira", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Conjunto Habitacional Capitão Eduardo", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Conjunto Habitacional Dom Silvério", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Conjunto Habitacional Fernão Dias", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Conjunto Habitacional Goiânia", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Conjunto Habitacional Lagoa", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Conjunto Habitacional Paulo VI (parte)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Conjunto Habitacional São Gabriel", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Conjunto Helena Antipoff", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Conjunto Itacolomi", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Conjunto Mariquinhas", regional: "Norte", bairroBHTrans: ""},
{bairro: "Conjunto Nova Pampulha", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Conjunto Pongelupe", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Conjunto Renato Ernesto do Nascimento", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Conjunto Santa Maria", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Conjunto Santa Maria", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Conjunto Túnel de Ibirité", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Conjunto Vila Rica", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Conjunto Zilah de Souza Spósito", regional: "Norte", bairroBHTrans: "CONJUNTO ZILAH SPOSITO"},
{bairro: "Conjunto Átila de Paiva", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Conselheiro Rocha", regional: "Leste", bairroBHTrans: ""},
{bairro: "Copacabana (parte)", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Copacabana", regional: "Venda Nova", bairroBHTrans: "COPACABANA"},
{bairro: "Coqueiros", regional: "Noroeste", bairroBHTrans: "COQUEIROS"},
{bairro: "Coração de Jesus", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Coração Eucarístico", regional: "Noroeste", bairroBHTrans: "CORACAO EUCARISTICO"},
{bairro: "Cristo Redentor", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Cruzeiro do Sul", regional: "Leste", bairroBHTrans: ""},
{bairro: "Cruzeiro do Sul", regional: "Leste", bairroBHTrans: ""},
{bairro: "Cruzeiro", regional: "Centro-Sul", bairroBHTrans: "CRUZEIRO"},
{bairro: "Céu Azul (4ª seção)", regional: "Pampulha", bairroBHTrans: "CEU AZUL"},
{bairro: "Cônego Pinheiro", regional: "Leste", bairroBHTrans: ""},
{bairro: "Diamante", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Dom Bosco", regional: "Noroeste", bairroBHTrans: "DOM BOSCO"},
{bairro: "Dom Cabral", regional: "Noroeste", bairroBHTrans: "DOM CABRAL"},
{bairro: "Dom Joaquim", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Dom Silvério", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Dona Clara", regional: "Pampulha", bairroBHTrans: "DONA CLARA"},
{bairro: "Edgard Wernek", regional: "Leste", bairroBHTrans: ""},
{bairro: "Engenho Nogueira", regional: "Pampulha", bairroBHTrans: "ENGENHO NOGUEIRA"},
{bairro: "Ermelinda", regional: "Noroeste", bairroBHTrans: "ERMELINDA"},
{bairro: "Esplanada I", regional: "Leste", bairroBHTrans: ""},
{bairro: "Esplanada II-A", regional: "Leste", bairroBHTrans: ""},
{bairro: "Esplanada II-B", regional: "Leste", bairroBHTrans: ""},
{bairro: "Esplanada", regional: "Leste", bairroBHTrans: ""},
{bairro: "Esplendor", regional: "Venda Nova", bairroBHTrans: "ESPLENDOR"},
{bairro: "Estoril", regional: "Oeste", bairroBHTrans: "ESTORIL"},
{bairro: "Etelvina Carneiro", regional: "Norte", bairroBHTrans: ""},
{bairro: "Europa", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Eymard", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Felicidade", regional: "Norte", bairroBHTrans: ""},
{bairro: "Fernão Dias", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Filadélfia", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Flamengo", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Floramar", regional: "Norte", bairroBHTrans: "FLORAMAR"},
{bairro: "Floresta", regional: "Leste", bairroBHTrans: ""},
{bairro: "Flávio Marques Lisboa", regional: "Barreiro", bairroBHTrans: "FLAVIO MARQUES LISBOA"},
{bairro: "Frei Eutáquio", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Freitas", regional: "Leste", bairroBHTrans: ""},
{bairro: "Funcionários", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Gameleira", regional: "Noroeste", bairroBHTrans: "GAMELEIRA"},
{bairro: "Gameleira", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Garças", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Gira Alves", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Glalija", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Glalijá", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Glória", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Goiânia", regional: "Nordeste", bairroBHTrans: "GOIANIA"},
{bairro: "Governador Benedito Val", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Grajaú", regional: "Oeste", bairroBHTrans: "GRAJAU"},
{bairro: "Granja de Freitas", regional: "Leste", bairroBHTrans: ""},
{bairro: "Guarani", regional: "Norte", bairroBHTrans: "GUARANI"},
{bairro: "Gutierrez", regional: "Oeste", bairroBHTrans: "GUTIERREZ"},
{bairro: "Havaí", regional: "Oeste", bairroBHTrans: "HAVAI"},
{bairro: "Heliópolis", regional: "Norte", bairroBHTrans: ""},
{bairro: "Horto Florestal", regional: "Leste", bairroBHTrans: ""},
{bairro: "Horto", regional: "Leste", bairroBHTrans: ""},
{bairro: "Inconfidência", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Indaiá", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Independência", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Instituto Agronômico", regional: "Leste", bairroBHTrans: "INSTITUTO AGRONOMICO"},
{bairro: "Ipanema", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Ipiranga", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Ipê", regional: "Nordeste", bairroBHTrans: "BAIRRO IPE"},
{bairro: "Itaipu", regional: "Barreiro", bairroBHTrans: "ITAIPU"},
{bairro: "Itapoã", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Itatiaia (conhecido também como Santa Terezinha)", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Jaqueline", regional: "Norte", bairroBHTrans: "JAQUELINE"},
{bairro: "Jaraguá", regional: "Pampulha", bairroBHTrans: "JARAGUA"},
{bairro: "Jardim Alvorada", regional: "Noroeste", bairroBHTrans: "JARDIM ALVORADA"},
{bairro: "Jardim América", regional: "Oeste", bairroBHTrans: "JARDIM AMERICA"},
{bairro: "Jardim Atlântico", regional: "Pampulha", bairroBHTrans: "JARDIM ATLANTICO"},
{bairro: "Jardim dos Comerciários", regional: "Venda Nova", bairroBHTrans: "JARDIM DOS COMERCIARIOS"},
{bairro: "Jardim Europa", regional: "Venda Nova", bairroBHTrans: "JARDIM EUROPA"},
{bairro: "Jardim Felicidade", regional: "Norte", bairroBHTrans: ""},
{bairro: "Jardim Guanabara", regional: "Norte", bairroBHTrans: "JARDIM GUANABARA"},
{bairro: "Jardim Leblon", regional: "Venda Nova", bairroBHTrans: "JARDIM LEBLON"},
{bairro: "Jardim Montanhês", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Jardim Vitória", regional: "Nordeste", bairroBHTrans: "JARDIM VITORIA"},
{bairro: "Jatobá IV", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Jatobá", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Jonas Veiga", regional: "Leste", bairroBHTrans: ""},
{bairro: "João Alfredo", regional: "Leste", bairroBHTrans: ""},
{bairro: "João Pinheiro", regional: "Noroeste", bairroBHTrans: "JOAO PINHEIRO"},
{bairro: "Juliana", regional: "Norte", bairroBHTrans: "JULIANA"},
{bairro: "Justinópolis", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Kátia", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Lagoa", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Lagoinha (parte)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Lagoinha", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Lajedo", regional: "Norte", bairroBHTrans: ""},
{bairro: "Letícia", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Liberdade", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Lindéia", regional: "Barreiro", bairroBHTrans: "LINDEIA"},
{bairro: "Lourdes", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Luxemburgo", regional: "Centro-Sul", bairroBHTrans: "LUXEMBURGO"},
{bairro: "Madre Gertrudes", regional: "Oeste", bairroBHTrans: "MADRE GERTRUDES"},
{bairro: "Manacás", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Mangabeiras", regional: "Centro-Sul", bairroBHTrans: "MANGABEIRAS"},
{bairro: "Mangueiras", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Mantiqueira", regional: "Venda Nova", bairroBHTrans: "MANTIQUEIRA"},
{bairro: "Marajó", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Maria Goretti", regional: "Nordeste", bairroBHTrans: "MARIA GORETTI"},
{bairro: "Maria Helena", regional: "Venda Nova", bairroBHTrans: "MARIA HELENA"},
{bairro: "Maria Virgínia", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Mariana", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Mariano de Abreu", regional: "Leste", bairroBHTrans: ""},
{bairro: "Marilândia", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Marize", regional: "Norte", bairroBHTrans: ""},
{bairro: "Milionários", regional: "Barreiro", bairroBHTrans: "MILIONARIOS"},
{bairro: "Milionários", regional: "Barreiro", bairroBHTrans: "BAIRRO MILIONARIOS"},
{bairro: "Minas Brasil", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Minas Caixa", regional: "Venda Nova", bairroBHTrans: "MINAS CAIXA"},
{bairro: "Minaslândia", regional: "Norte", bairroBHTrans: ""},
{bairro: "Mineirão", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Miramar", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Monsenhor Messias", regional: "Noroeste", bairroBHTrans: "MONSENHOR MESSIAS"},
{bairro: "Monte Azul", regional: "Norte", bairroBHTrans: ""},
{bairro: "Monte Azul", regional: "Norte", bairroBHTrans: ""},
{bairro: "Monte de São José", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Morro das Pedras", regional: "Oeste", bairroBHTrans: "MORRO DAS PEDRAS"},
{bairro: "Morro do Papagaio", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Nazaré", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Nossa Senhora da Conceição", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Nova América", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Nova Barroca", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Nova Cachoeirinha", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Nova Cintra", regional: "Oeste", bairroBHTrans: "NOVA CINTRA"},
{bairro: "Nova Esperança", regional: "Noroeste", bairroBHTrans: "NOVA ESPERANCA"},
{bairro: "Nova Floresta", regional: "Nordeste", bairroBHTrans: "NOVA FLORESTA"},
{bairro: "Nova Gameleira", regional: "Oeste", bairroBHTrans: "NOVA GAMELEIRA"},
{bairro: "Nova Granada", regional: "Oeste", bairroBHTrans: "NOVA GRANADA"},
{bairro: "Nova Suíça", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Nova Vista", regional: "Leste", bairroBHTrans: "NOVA VISTA"},
{bairro: "Nova York", regional: "Venda Nova", bairroBHTrans: "NOVA YORK"},
{bairro: "Novo Aarão Reis (parte)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Novo Aarão Reis", regional: "Norte", bairroBHTrans: ""},
{bairro: "Novo Anchieta", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Novo das Indústrias", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Novo Horizonte", regional: "Leste", bairroBHTrans: ""},
{bairro: "Novo Itapuã", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Novo Letícia", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Novo Ouro Preto", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Novo Santa Cecília", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Novo Sion", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Novo São Lucas", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Novo São Lucas", regional: "Leste", bairroBHTrans: ""},
{bairro: "Olaria", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Olhos d'Água (parte)", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Olhos d'Água", regional: "Barreiro", bairroBHTrans: "OLHOS D AGUA"},
{bairro: "Olhos d'Água", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Ouro Minas", regional: "Nordeste", bairroBHTrans: "OURO MINAS"},
{bairro: "Ouro Preto", regional: "Pampulha", bairroBHTrans: "OURO PRETO"},
{bairro: "Ouro Preto", regional: "Pampulha", bairroBHTrans: "OURO PRETO 3A GLEBA"},
{bairro: "Padre Eustáquio", regional: "Noroeste", bairroBHTrans: "PADRE ESTAQUIO"},
{bairro: "Padre Eustáquio", regional: "Noroeste", bairroBHTrans: "PADRE EUSTAQUIO"},
{bairro: "Palmares", regional: "Nordeste", bairroBHTrans: "PALMARES"},
{bairro: "Palmeiras", regional: "Oeste", bairroBHTrans: "PALMEIRAS"},
{bairro: "Pampulha", regional: "Pampulha", bairroBHTrans: "PAMPULHA"},
{bairro: "Paquetá", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Paraíso I", regional: "Leste", bairroBHTrans: "PARAISO"},
{bairro: "Paraíso II", regional: "Leste", bairroBHTrans: ""},
{bairro: "Paraúna", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Parque Cidade Jardim", regional: "Leste", bairroBHTrans: ""},
{bairro: "Parque Nossa Senhora do Rosário", regional: "Leste", bairroBHTrans: ""},
{bairro: "Parque Riachuelo", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Parque São José", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Patrocínio", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Paulo VI (parte)", regional: "Nordeste", bairroBHTrans: "PAULO VI"},
{bairro: "Pedreira Prado Lopes", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Pedro II", regional: "Noroeste", bairroBHTrans: "PEDRO II"},
{bairro: "Petrópolis", regional: "Barreiro", bairroBHTrans: "PETROPOLIS"},
{bairro: "Pilar", regional: "Barreiro", bairroBHTrans: "PILAR"},
{bairro: "Pilar", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Pindorama", regional: "Noroeste", bairroBHTrans: "PINDORAMA"},
{bairro: "Pirajá", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Piratininga", regional: "Venda Nova", bairroBHTrans: "PIRATININGA"},
{bairro: "Pirineus", regional: "Leste", bairroBHTrans: ""},
{bairro: "Planalto", regional: "Norte", bairroBHTrans: "PLANALTO"},
{bairro: "Política", regional: "Leste", bairroBHTrans: ""},
{bairro: "Pompeia", regional: "Leste", bairroBHTrans: "POMPEIA"},
{bairro: "Pousada Santo Antônio", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Prado", regional: "Oeste", bairroBHTrans: "PRADO"},
{bairro: "Primavera", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Providência", regional: "Norte", bairroBHTrans: "PROVIDENCIA"},
{bairro: "Renascença", regional: "Nordeste", bairroBHTrans: "RENASCENCA"},
{bairro: "Ribeiro de Abreu (Conjunto Ribeiro de Abreu)", regional: "Norte", bairroBHTrans: "RIBEIRO DE ABREU"},
{bairro: "Rio Branco", regional: "Venda Nova", bairroBHTrans: "RIO BRANCO"},
{bairro: "Sagrada Família", regional: "Leste", bairroBHTrans: "SAGRADA FAMILIA"},
{bairro: "Salgado Filho", regional: "Oeste", bairroBHTrans: "SALGADO FILHO"},
{bairro: "Santa Amélia", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Santa Branca", regional: "Pampulha", bairroBHTrans: "SANTA BRANCA"},
{bairro: "Santa Cecília", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Santa Cruz", regional: "Nordeste", bairroBHTrans: "SANTA CRUZ"},
{bairro: "Santa Efigênia", regional: "Leste", bairroBHTrans: "SANTA EFIGENIA"},
{bairro: "Santa Helena", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Santa Ifigênia", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Santa Inês", regional: "Leste", bairroBHTrans: "SANTA INES"},
{bairro: "Santa Isabel", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Santa Lúcia (parte)", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Santa Lúcia", regional: "Centro-Sul", bairroBHTrans: "ALTO SANTA LUCIA"},
{bairro: "Santa Lúcia", regional: "Centro-Sul", bairroBHTrans: "SANTA LUCIA"},
{bairro: "Santa Margarida", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Santa Maria", regional: "Noroeste", bairroBHTrans: "SANTA MARIA"},
{bairro: "Santa Mônica", regional: "Pampulha", bairroBHTrans: "SANTA MONICA"},
{bairro: "Santa Rita", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Santa Rosa", regional: "Pampulha", bairroBHTrans: "SANTA ROSA"},
{bairro: "Santa Teresinha", regional: "Pampulha", bairroBHTrans: "SANTA TEREZINHA"},
{bairro: "Santa Tereza", regional: "Leste", bairroBHTrans: "SANTA TERESA"},
{bairro: "Santana do Cafezal", regional: "Leste", bairroBHTrans: ""},
{bairro: "Santo Agostinho", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Santo André", regional: "Noroeste", bairroBHTrans: "SANTO ANDRE"},
{bairro: "Santo Antônio", regional: "Centro-Sul", bairroBHTrans: "SANTO ANTONIO"},
{bairro: "Santos Torres", regional: "Leste", bairroBHTrans: ""},
{bairro: "Saramenha", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Sarandí", regional: "Pampulha", bairroBHTrans: "SARANDI"},
{bairro: "Saudade", regional: "Leste", bairroBHTrans: "SAUDADE"},
{bairro: "Savassi", regional: "Centro-Sul", bairroBHTrans: "SAVASSI"},
{bairro: "Serra (8ª seção suburbana, Belo Horizonte)", regional: "Leste", bairroBHTrans: ""},
{bairro: "Serra do José Vieira", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Serra do José Vieira", regional: "Oeste", bairroBHTrans: ""},
{bairro: "Serra Verde", regional: "Venda Nova", bairroBHTrans: "SERRA VERDE"},
{bairro: "Serra", regional: "Centro-Sul", bairroBHTrans: "SERRA"},
{bairro: "Serrano", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Serrano", regional: "Pampulha", bairroBHTrans: "SERRANO"},
{bairro: "Silveira", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Sinimbu", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Sion", regional: "Centro-Sul", bairroBHTrans: "SION"},
{bairro: "Soberana", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Sol Nascente", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Solar do Barreiro", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Solar", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Solimões", regional: "Norte", bairroBHTrans: ""},
{bairro: "Sumaré", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Suzana", regional: "Pampulha", bairroBHTrans: "SUZANA"},
{bairro: "São Bento", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "São Bernardo", regional: "Norte", bairroBHTrans: ""},
{bairro: "São Bernardo", regional: "Pampulha", bairroBHTrans: "SAO BERNARDO"},
{bairro: "São Cristóvão (parte)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "São Cristóvão", regional: "Noroeste", bairroBHTrans: "SAO CRISTOVAO"},
{bairro: "São Francisco", regional: "Pampulha", bairroBHTrans: "SAO FRANCISCO"},
{bairro: "São Gabriel", regional: "Nordeste", bairroBHTrans: "PUC-SAO GABRIEL"},
{bairro: "São Gabriel", regional: "Nordeste", bairroBHTrans: "SAO GABRIEL"},
{bairro: "São Geraldo", regional: "Leste", bairroBHTrans: "SAO GERALDO"},
{bairro: "São José", regional: "Pampulha", bairroBHTrans: "SAO JOSE"},
{bairro: "São José/Gorduras", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "São João Batista", regional: "Venda Nova", bairroBHTrans: "SAO JOAO BATISTA"},
{bairro: "São João", regional: "Leste", bairroBHTrans: ""},
{bairro: "São Lucas", regional: "Centro-Sul", bairroBHTrans: "SAO LUCAS"},
{bairro: "São Lucas", regional: "Leste", bairroBHTrans: ""},
{bairro: "São Luís", regional: "Pampulha", bairroBHTrans: "SAO LUIS"},
{bairro: "São Marcos", regional: "Nordeste", bairroBHTrans: "SAO MARCOS"},
{bairro: "São Paulo", regional: "Nordeste", bairroBHTrans: "SAO PAULO"},
{bairro: "São Paulo", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "São Pedro", regional: "Centro-Sul", bairroBHTrans: "SAO PEDRO"},
{bairro: "São Rafael", regional: "Leste", bairroBHTrans: ""},
{bairro: "São Salvador", regional: "Noroeste", bairroBHTrans: "SAO SALVADOR"},
{bairro: "São Tomás (parte)", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "São Vicente", regional: "Leste", bairroBHTrans: ""},
{bairro: "Taquaril", regional: "Leste", bairroBHTrans: "TAQUARIL"},
{bairro: "Teixeira Dias", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Teresa Cristina A", regional: "Leste", bairroBHTrans: ""},
{bairro: "Tirol", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Trevo", regional: "Pampulha", bairroBHTrans: "TREVO"},
{bairro: "Tupi A", regional: "Norte", bairroBHTrans: ""},
{bairro: "Tupi B", regional: "Norte", bairroBHTrans: ""},
{bairro: "Tupi", regional: "Norte", bairroBHTrans: "TUPI"},
{bairro: "Universitário", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Universo", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "União", regional: "Nordeste", bairroBHTrans: "UNIAO"},
{bairro: "Urca", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Urucuia", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vale do Jatobá", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Venda Nova", regional: "Venda Nova", bairroBHTrans: "VENDA NOVA"},
{bairro: "Vera Cruz", regional: "Leste", bairroBHTrans: "VERA CRUZ"},
{bairro: "Vila Acaba Mundo", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Aeroporto", regional: "Norte", bairroBHTrans: ""},
{bairro: "Vila Alta Tensão", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Antena", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Antônio Ribeiro de Abreu", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Aparecida", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Apolônia", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Artur de Sá", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Bacuraus", regional: "Norte", bairroBHTrans: ""},
{bairro: "Vila Beija-flor (Borges)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Bernadete", regional: "Barreiro", bairroBHTrans: "VILA BERNADETE"},
{bairro: "Vila Biquinhas", regional: "Norte", bairroBHTrans: ""},
{bairro: "Vila Boa União (parte)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Boa União", regional: "Norte", bairroBHTrans: ""},
{bairro: "Vila Brasília (Guanabara)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Cafezal", regional: "Centro-Sul", bairroBHTrans: "VILA CAFEZAL"},
{bairro: "Vila Capri", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Carioca", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Castanheiras", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Cemig", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Clóris", regional: "Norte", bairroBHTrans: ""},
{bairro: "Vila Copacabana", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Copasa", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Coqueiro (Beco)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Corococó", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila da Paz", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila do Pombal", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila do Índio", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Vila dos Anjos", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Estrela", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Estrela", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Formosa", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Grota", regional: "Leste", bairroBHTrans: ""},
{bairro: "Vila Humaitá (Inestan)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Ipiranga", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Isabel", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Vila Itamarati", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Jardim do Vale", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Mantiqueira", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Maria Virgínia", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Vila Maria", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Marieta", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Marçola", regional: "Centro-Sul", bairroBHTrans: "VILA MARCOLA"},
{bairro: "Vila Matadouro", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Minas Caixa", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Morro do Querosene", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Mãe dos Pobres", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Nossa Senhora Aparecida", regional: "Leste", bairroBHTrans: ""},
{bairro: "Vila Nossa Senhora Aparecida", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Nossa Senhora de Fátima", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Nossa Senhora do Rosário", regional: "Leste", bairroBHTrans: ""},
{bairro: "Vila Nova Cachoeirinha III", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Nova Cachoeirinha IV", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Nova dos Milionários", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Oeste", regional: "Noroeste", bairroBHTrans: "VILA OESTE"},
{bairro: "Vila Papagaio", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Paquetá", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Vila Paris", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Petrópolis", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Pindura Saia", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Pinho", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Piratininga", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Presidente Vargas (São Benedito)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Real", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Vila Rock in Rio", regional: "Leste", bairroBHTrans: ""},
{bairro: "Vila Santa Branca", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Santa Cruz", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Vila Santa Lúcia", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Santa Maria", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Santa Rita", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Vila Santa Rosa", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Vila Santana do Cafezal", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Serra Verde", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila Sesc", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila São José", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila São João Batista", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Vila São Miguel", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Vila São Paulo (Andiroba, Modelo, Praça da Associação, Suzana)", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila São Tomás", regional: "Norte", bairroBHTrans: ""},
{bairro: "Vila São Vicente", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Vila Tiradentes", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Três Marias", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Unida", regional: "Pampulha", bairroBHTrans: ""},
{bairro: "Vila Universitário", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Virgínia", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "Vila Vista do Sol", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Vila Ápia", regional: "Centro-Sul", bairroBHTrans: ""},
{bairro: "Vila Área", regional: "Leste", bairroBHTrans: ""},
{bairro: "Vista Alegre", regional: "Oeste", bairroBHTrans: "VISTA ALEGRE"},
{bairro: "Vista do Sol", regional: "Nordeste", bairroBHTrans: ""},
{bairro: "Várzea das Palmas", regional: "Venda Nova", bairroBHTrans: ""},
{bairro: "Washington Pires", regional: "Barreiro", bairroBHTrans: ""},
{bairro: "Xangrilá", regional: "Pampulha", bairroBHTrans: "XANGRILA"},
{bairro: "Xodó", regional: "Norte", bairroBHTrans: "XODO"},
{bairro: "Álvaro Camargos", regional: "Noroeste", bairroBHTrans: ""},
{bairro: "", regional: "Leste", bairroBHTrans: "AV. DO CONTORNO"},
{bairro: "", regional: "Oeste", bairroBHTrans: "BAIRRO DAS INDUSTRIAS"},
{bairro: "", regional: "Nordeste", bairroBHTrans: "BAIRRO VITORIA"},
{bairro: "", regional: "Noroeste", bairroBHTrans: "BELA VISTA"},
{bairro: "", regional: "Oeste", bairroBHTrans: "BH SHOPPING"},
{bairro: "", regional: "Norte", bairroBHTrans: "CAMPO ALEGRE"},
{bairro: "", regional: "Centro-Sul", bairroBHTrans: "CENTRO"},
{bairro: "", regional: "Venda Nova", bairroBHTrans: "CIDADE ADMINISTRATIVA"},
{bairro: "", regional: "Contagem", bairroBHTrans: "CIDADE INDUSTRIAL"},
{bairro: "", regional: "Leste", bairroBHTrans: "CIRCULAR"},
{bairro: "", regional: "Pampulha", bairroBHTrans: "CONFISCO"},
{bairro: "", regional: "Barreiro", bairroBHTrans: "ESCOLA"},
{bairro: "", regional: "Centro-Sul", bairroBHTrans: "EST. CENTRAL"},
{bairro: "", regional: "Barreiro", bairroBHTrans: "ESTACAO BARREIRO"},
{bairro: "", regional: "Oeste", bairroBHTrans: "ESTACAO CALAFATE"},
{bairro: "", regional: "Barreiro", bairroBHTrans: "ESTACAO DIAMANTE"},
{bairro: "", regional: "Leste", bairroBHTrans: "ESTACAO JOSE CANDIDO"},
{bairro: "", regional: "Nordeste", bairroBHTrans: "ESTACAO SAO GABRIEL"},
{bairro: "", regional: "Venda Nova", bairroBHTrans: "ESTACAO VENDA NOVA"},
{bairro: "", regional: "Noroeste", bairroBHTrans: "ESTACAO VILA OESTE"},
{bairro: "", regional: "Venda Nova", bairroBHTrans: "ESTACAO VILARINHO"},
{bairro: "", regional: "Oeste", bairroBHTrans: "ESTRELA DO ORIENTE"},
{bairro: "", regional: "Noroeste", bairroBHTrans: "JARDIM FILADELFIA"},
{bairro: "", regional: "Pampulha", bairroBHTrans: "JARDIM INCONFIDENCIA"},
{bairro: "", regional: "Venda Nova", bairroBHTrans: "LANDI"},
{bairro: "", regional: "Oeste", bairroBHTrans: "METRO CALAFATE"},
{bairro: "", regional: "Nordeste", bairroBHTrans: "MINAS SHOPPING"},
{bairro: "", regional: "Noroeste", bairroBHTrans: "NOSSA SENHORA DA GLORIA"},
{bairro: "", regional: "Leste", bairroBHTrans: "NOSSA SENHORA DE FATIMA"},
{bairro: "", regional: "Pampulha", bairroBHTrans: "NOVA PAMPULHA"},
{bairro: "", regional: "Noroeste", bairroBHTrans: "NOVO DOM BOSCO"},
{bairro: "", regional: "Nordeste", bairroBHTrans: "POUSADA SANTO ANTONIO"},
{bairro: "", regional: "Principal", bairroBHTrans: "PRINCIPAL"},
{bairro: "", regional: "Barreiro", bairroBHTrans: "REGINA"},
{bairro: "", regional: "Noroeste", bairroBHTrans: "SHOPPING DEL REY"},
{bairro: "", regional: "Pampulha", bairroBHTrans: "UFMG ESCOLA DE BELAS ARTES"},
{bairro: "", regional: "Oeste", bairroBHTrans: "UPA OESTE"},
{bairro: "", regional: "Oeste", bairroBHTrans: "VILA LEONINA"},
{bairro: "", regional: "Pampulha", bairroBHTrans: "ZOOLOGICO"}
];
